name: Generate Data Source

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # 원하는 Node.js 버전 설정

      - name: Install dependencies
        run: npm install

      - name: Transpile TypeScript
        run: npm run build

      - name: Generate JSON file
        run: npm run start

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-artifact
          path: .out/shops.json
