name: Generate Data Source

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # 원하는 Node.js 버전 설정

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}" >> .env
          echo "NAVER_CLOUD_PLATFORM_CLIENT_ID=${{ secrets.NAVER_CLOUD_PLATFORM_CLIENT_ID }}" >> .env
          echo "NAVER_CLOUD_PLATFORM_CLIENT_SECRET=${{ secrets.NAVER_CLOUD_PLATFORM_CLIENT_SECRET }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Transpile TypeScript
        run: npm run build

      - name: Sync data source
        run: npm run start
